package: article_presets
version: '1.2.0'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/article_presets

page:
    title: 'translate:title'
    perm: article_presets[]
    pjax: true
    icon: rex-icon fa-files-o
    subpages:
        profiles: { title: 'translate:profiles', perm: article_presets[profiles] }

requires:
    redaxo: '>=5.1.0'
